version: '3'

services:
  db:
    image: postgres
    volumes:
      - db-data:/home/angel/Proyectos/pingotron-data
    environment:
      - POSTGRES_USER=pingotron
      - POSTGRES_PASSWORD=pingotron
    
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db